# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f7fe033673f34908a4b98a5607933b74e2366767ba193dcf136e79dedd23c50f8b1398b0c4da89afa1cbbcf7d07216b543f1d0ade923b799202fea5c478206e2

test:
  secret_key_base: aeccceda3c9e1e6a9b10cae882a9a9055ad1a00a5afe2fef882a0ba3da19b697d955cba2416228cb4d42b6935cfea3e9b7516ce218248570ceec28da91ff1977

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
